# Generated by Django 6.0.3 on 2026-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_internaltransfer_internaltransferitem_stockquant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("vendor", "Vendor"),
                    ("customer", "Customer"),
                    ("loss", "Loss"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uom",
            field=models.CharField(
                default="pcs",
                help_text="Unit of measure (pcs, kg, litre, box, etc.).",
                max_length=20,
            ),
        ),
    ]
