# Generated by Django 6.0.3 on 2026-03-14 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_location_location_type_alter_product_uom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated reference, e.g. 'WH/IN/0001'.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("delivery", "Delivery"),
                            ("internal", "Internal"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("waiting", "Waiting"),
                            ("ready", "Ready"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier (receipts) or Customer (deliveries).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations",
                        to="inventory.contact",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the goods are going (used for receipts & transfers).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_in",
                        to="inventory.location",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the goods come from (used for deliveries & transfers).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_out",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_qty", models.PositiveIntegerField(default=0)),
                ("received_qty", models.PositiveIntegerField(default=0)),
                (
                    "done_qty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Picked / processed quantity (used for deliveries).",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.operation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_lines",
                        to="inventory.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "operation_ref",
                    models.CharField(
                        db_index=True,
                        help_text="Reference of the source Operation, e.g. 'WH/IN/0001'.",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source location (NULL for vendor / external supply).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_out",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="inventory.product",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination location (NULL for customer / external demand).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_in",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Ledger Entry",
                "verbose_name_plural": "Stock Ledger Entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
