# Generated by Django 6.0.3 on 2026-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_done_qty_to_operationline"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Inventory Manager"),
                    ("staff", "Warehouse Staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
