# Generated by Django 6.0.3 on 2026-03-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor (receipts) or Customer (deliveries) associated with this entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="inventory.contact",
            ),
        ),
    ]
